New York Times Service Submodule + External Submodule Integration
elagarrigue/AyDS23-NewYork4 pull request #17
Opened 2023-06-01 04:12 UTC by zeke0816

On this branch, we extracted the external repository used to obtain information about an artist from The New York Times API into its own, new repository, and added it to this repository as a submodule via Git. Then, we created an abstraction of what we knew as `Artist` and `NYTimesArtist` in the form of the `Card` class.

This `Card` class allows us to store the same information as before, but agnostic of the source of information. For example, it would not matter if the information came from *The New York Times* or *The Washington Post*, but rather the kind of information that we receive and ultimately store locally.

The other sources of information were provided by other teams, namely `Lisbon1` and `Winchester3`. They provided `LastFM` and `Wikipedia`, respectively. In order to adapt the nomenclature provided by their repositories, we implemented a `Broker` architecture using a `Proxy` and some `Resolvers`. The `Broker` uses the different `Proxies` to get a `Card` filled with information coming in from the different external sources. The `Proxies` do this by using the corresponding external services (APIs) and `Resolvers` to map out the received information to our implementation of the `Card` class, eventually returning an instance of the `Card` class or `null`.

Last, but not least, we:

- updated the presentation layer of our Clean MVP implementation to reflect the changes,
- updated the testers developed in the last assignment, and
- adapted our local storage solution in SQLite by defining new columns and updating the functions that manage our database projections and queries.

2023-06-01 04:16 UTC, zeke0816 commented
The last commit resolved PR conflicts.

2023-06-02 21:06 UTC, FabioCampetti commented on app/src/main/java/ayds/newyork/songinfo/moredetails/data/repository/CardBroker.kt
> +    private val nyTimesArtistProxy: ArtistProxy,
Definir una interfaz porxy service, y luego definir una clase proxy para cada servicioExterno.
Aca utilizar una lista con todos los proxy

2023-06-02 21:16 UTC, FabioCampetti commented on app/src/main/java/ayds/newyork/songinfo/moredetails/data/repository/externalServiceProxy/ArtistToCardResolver.kt
> +class NYTimesArtistToCardResolver {
Deinifr un resolver para cada serivicio

2023-06-02 23:01 UTC, FabioCampetti commented
Broker tiene que estar dentro de data/repository/external (se rompe con la estructura de la arquitectura)

2023-06-02 23:13 UTC, FabioCampetti commented on app/src/main/java/ayds/newyork/songinfo/moredetails/data/repository/externalServiceProxy/ArtistProxy.kt
> +interface ArtistProxy {
Rename to ServiceProxy

2023-06-02 23:51 UTC, FabioCampetti commented on app/src/main/java/ayds/newyork/songinfo/moredetails/presentation/presenter/MoreDetailsPresenter.kt
> +        updateNoResultsUiState()
No tiene sentido hacer una update sin resultado y luego otro con el resultado. Se deberia hacer uno o el otro

2023-06-02 23:51 UTC, FabioCampetti commented on app/src/main/java/ayds/newyork/songinfo/moredetails/presentation/presenter/MoreDetailsPresenter.kt
> +    private fun updateNoResultsUiState() {
Esto solo deja una lista vacia. Se deberia mostrar que no hubo resutlados o no encontrado.

2023-06-03 20:04 UTC, kevschweitzer commented
Actualicen tambien el diagrama de clases. De los submodulos hagan lo interior del suyo nomas. Los otros pongan solo el paquete para representarlo

2023-06-07 13:35 UTC, kevschweitzer requested changes
Diagrama de clases:
- Servicio externo
- Linea de Domain a Presentation no va
- Donde esta la view?
- Flecha de herencia del repository no es de herencia
- Flecha de broker tiene que ir a la interfaz de Proxy (recibe una lista de proxy). Ademas diferenciar las flechas a cada servicio desde cada implementacion de proxy. 
- No pongan los inyectors
- Falta una flecha de repository a local
- La flecha del home tiene que ir al paquete general, no adentro
- CardLocalStorageImpl tiene que conocer a la interfaz del mapper

2023-06-07 13:35 UTC, kevschweitzer commented on app/src/main/java/ayds/newyork/songinfo/moredetails/data/repository/externalServiceProxy/LastFMServiceProxy.kt
> +    private fun createEmptyCard(): Card {
No poner EmptyCards en la lista de respuesta. Si no se encuentra nada se usa la lista vacia. EmptyCard tiene sentido si es una sola, en la lista la respuesta vacia es mejor usando lista vacia

2023-06-07 13:35 UTC, kevschweitzer commented on app/src/main/java/ayds/newyork/songinfo/moredetails/presentation/presenter/MoreDetailsPresenter.kt
>      var uiState: MoreDetailsUiState
uiState tiene que ser val acá

2023-06-07 13:35 UTC, kevschweitzer commented on app/src/main/java/ayds/newyork/songinfo/moredetails/presentation/presenter/MoreDetailsPresenter.kt
> +        for (card: Card in cards){
*CONSEJO* pueden usar un .map

2023-06-07 21:02 UTC, zeke0816 commented on app/src/main/java/ayds/newyork/songinfo/moredetails/presentation/presenter/MoreDetailsPresenter.kt
>      var uiState: MoreDetailsUiState
@kevschweitzer Esto es algo que no supimos cómo cambiar debido a que debemos actualizar `uiState` en un momento y eso lo hacemos a través de `uiState = uiState.copy(...)`. Esta asignación solo se puede hacer si `uiState` es `var`, no `val`. Lo único que se nos ocurre es que lo que está adentro de `MoreDetailsUiState` (`cards`) sea `var`. ¿Cómo podemos avanzar?

2023-06-09 13:50 UTC, kevschweitzer commented on app/src/main/java/ayds/newyork/songinfo/moredetails/presentation/presenter/MoreDetailsPresenter.kt
>      var uiState: MoreDetailsUiState
En la interfaz es val pero se hace override como var. Fijense en Home. De esa manera quienes tienen acceso a la interfaz (la vista) solo puede consumir el UIState, no cambiarlo, y el unico que lo puede cambiar es el presenter

2023-06-09 13:52 UTC, zeke0816 commented on app/src/main/java/ayds/newyork/songinfo/moredetails/presentation/presenter/MoreDetailsPresenter.kt
>      var uiState: MoreDetailsUiState
@kevschweitzer Perfecto, muchas gracias. Vamos a probar así y te solicitamos revisión.

2023-06-10 23:44 UTC, kevschweitzer requested changes
Diagrama de clases:
- Paquetes externos como SQL, Lisboa y Wikipedia simplemente hacer un recuadro que diga ese nombre y listo. No hacer todos los paquetes. Ademas que no esten dentro de una carpeta ayds. Que estén sueltos
- Tambien para el servicio externo de ustedes no hace falta todo el diagrama de paquetes que lo envuelve. Simplemente ponganle NewYorkTimes  o algo asi
- Falta la flecha de la impl del presenter a la interfaz del helper
- Falta la flecha desde la view al presenter
- Falta la flecha del repository impl al broker
- Las flechas que significan "conoce" deben ser solidas (Como la que va al servicio de NY). Fijense que está distinta con las que van a los otros servicios
- Porque hay una carpeta que se llama NyTimes en Local? Esa no va
- Veo que tienen mal el sistema de paquetes del repository. External y local tienen que estar al mismo nivel. Puede ser un paquete repository y que dentro esten external y local y el repository conozca a ambos paquetes

2023-06-12 14:50 UTC, merged